# Generated by Django 4.2 on 2026-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('ai_response', models.TextField(blank=True)),
                ('status', models.CharField(default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
