# Generated by Django 4.2 on 2026-09-09 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
        migrations.AddField(
            model_name='lead',
            name='interest',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified')], default='New', max_length=20),
        ),
    ]
